#!/usr/bin/env bash
# =============================================================================
# Secret generation
# =============================================================================
#   make secrets            generate .env and secrets/ if they do not exist
#   make secrets FORCE=1    regenerate everything, replacing existing values
#
# Produces two things:
#
#   .env                    copied from .env.example with every CHANGEME_*
#                           placeholder replaced by a fresh random value
#   secrets/local/*.txt     file-backed Docker secrets for images that support
#                           reading a credential from a file
#
# `.env` and `secrets/local/` are git-ignored. The tracked `secrets/*.txt`
# files remain untouched as the clearly-labelled defaults used by a bare
# `docker compose up -d` with no `.env` file.
#
# Why this is a separate step rather than something the stack does itself:
# Compose resolves secrets and environment variables when it *parses* the
# project, before any container exists. Nothing running inside the lab can
# generate a credential the lab itself needs at parse time.
# =============================================================================
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

ENV_FILE="${LAB_ROOT}/.env"
ENV_EXAMPLE="${LAB_ROOT}/.env.example"
SECRETS_DIR="${LAB_ROOT}/secrets/local"
SECRETS_DIR_REL="./secrets/local"
FORCE="${FORCE:-0}"

# Docker secrets: filename → description
SECRET_FILES=(
  "postgres_password.txt:PostgreSQL superuser"
  "minio_root_password.txt:MinIO root user"
  "grafana_admin_password.txt:Grafana administrator"
)

# -----------------------------------------------------------------------------
# .env
# -----------------------------------------------------------------------------
generate_env_file() {
  if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
    warn ".env already exists — leaving it alone."
    log "  ${C_DIM}Regenerate with: make secrets FORCE=1  (this replaces every credential)${C_RESET}"
    return 0
  fi

  [[ -f "$ENV_EXAMPLE" ]] || die ".env.example is missing; cannot generate .env"

  if [[ -f "$ENV_FILE" ]]; then
    local backup
    backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$ENV_FILE" "$backup"
    warn "existing .env backed up to $(basename "$backup")"
  fi

  info "generating .env from .env.example"

  # Walk the example line by line, replacing only the placeholder values. This
  # preserves every comment, which is most of the file's value.
  local replaced=0
  : > "$ENV_FILE"
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^([A-Z_][A-Z0-9_]*)=CHANGEME_ ]]; then
      local key="${BASH_REMATCH[1]}"
      printf '%s=%s\n' "$key" "$(random_password 32)" >> "$ENV_FILE"
      (( replaced++ )) || true
    else
      printf '%s\n' "$line" >> "$ENV_FILE"
    fi
  done < "$ENV_EXAMPLE"

  harden_permissions "$ENV_FILE"
  success "wrote .env with ${replaced} generated credentials"
}

ensure_local_secrets_dir() {
  if ! grep -q '^LAB_SECRETS_DIR=' "$ENV_FILE" 2>/dev/null; then
    printf '\n# File-backed credentials generated by make secrets.\nLAB_SECRETS_DIR=%s\n' \
      "$SECRETS_DIR_REL" >> "$ENV_FILE"
    harden_permissions "$ENV_FILE"
    info "configured .env to use secrets/local/"
  fi
}

# -----------------------------------------------------------------------------
# Docker secrets
# -----------------------------------------------------------------------------
generate_secret_files() {
  mkdir -p "$SECRETS_DIR"

  local entry filename description path
  for entry in "${SECRET_FILES[@]}"; do
    filename="${entry%%:*}"
    description="${entry#*:}"
    path="${SECRETS_DIR}/${filename}"

    # A file that still holds the shipped placeholder is always replaced, even
    # without FORCE — leaving a known-value credential in place would defeat
    # the entire point of running this script.
    if [[ -f "$path" && "$FORCE" != "1" ]] && ! grep -q "insecure-dev-only" "$path" 2>/dev/null; then
      log "  ${C_DIM}kept${C_RESET} ${filename} ${C_DIM}(${description})${C_RESET}"
      continue
    fi

    # No trailing newline: several images read the file verbatim, and a stray
    # \n silently becomes part of the password.
    printf '%s' "$(random_password 32)" > "$path"
    harden_permissions "$path"
    success "wrote ${filename} ${C_DIM}(${description})${C_RESET}"
  done
}

# -----------------------------------------------------------------------------
# Permissions
#
# chmod is meaningless on a Windows filesystem, so a failure here is reported
# rather than fatal — the file is still generated, it is just not protected by
# POSIX permissions.
# -----------------------------------------------------------------------------
harden_permissions() {
  local path="$1"
  chmod 600 "$path" 2>/dev/null || true
}

# -----------------------------------------------------------------------------
# Sanity check: catch the case where generation silently produced nothing
# usable, which is far worse than failing loudly.
# -----------------------------------------------------------------------------
verify() {
  local problems=0

  # Anchored to an assignment: the word CHANGEME_ also appears in .env.example's
  # own explanatory comments, which are copied through verbatim and are fine.
  if grep -qE '^[A-Z_][A-Z0-9_]*=CHANGEME_' "$ENV_FILE" 2>/dev/null; then
    error "some CHANGEME_ placeholders survived in .env"
    grep -nE '^[A-Z_][A-Z0-9_]*=CHANGEME_' "$ENV_FILE" | head -5 | sed 's/^/    /'
    (( problems++ )) || true
  fi

  local entry filename path
  for entry in "${SECRET_FILES[@]}"; do
    filename="${entry%%:*}"
    path="${SECRETS_DIR}/${filename}"
    if [[ ! -s "$path" ]]; then
      error "${filename} is missing or empty"
      (( problems++ )) || true
    elif grep -q "insecure-dev-only" "$path" 2>/dev/null; then
      warn "${filename} still contains the shipped placeholder"
    fi
  done

  (( problems == 0 )) || die "secret generation did not complete cleanly"
}

main() {
  heading "Generating credentials"

  generate_env_file
  ensure_local_secrets_dir
  generate_secret_files
  verify

  log ""
  success "credentials ready"
  log "  ${C_DIM}View them any time with:${C_RESET} make creds"
  log ""
  log "  ${C_DIM}File-backed credentials are in secrets/local/ (git-ignored).${C_RESET}"

  if [[ "$FORCE" == "1" ]]; then
    log ""
    warn "Credentials changed. Services that stored the OLD password in their"
    warn "database — Keycloak, Gitea, Grafana, MinIO — will not accept the new"
    warn "one until their volumes are recreated:"
    log "    ${C_CYAN}make clean && make up${C_RESET}"
  fi
}

main "$@"
